/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/
#include "Platform_Types.h"
#include "EXTI.h"
#include "Register.h"


void clock_init(){
	//Enable PortA clock by set bit 2 in RCC_APB2ENR
	//Enable AFIO clock by set bit 0 in RCC_APB2ENR
	RCC_APB2ENR|=(1<<2)|(1<<0);
	//Wait to enable clock
	for(int i=0;i<2;i++);
}

void GPIO_init(){
	//Pin A2 : Floating input (reset state)
	GPIOA_CRL|=(1<<2);
	//Pin A13 : Output
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;
}

void NVIC_init(){
	//Enable EXTI0 in NVIC
	NIVC_ER_ISR0_31|=(1<<6);
}

void EXTI_Task(){
	//Toggle pin A13
	GPIOA_ODR^=(1<<13);
}

int main(void)
{
	EXTI_Config_t EXTI0_Config={EXTI0,PA,RAISING};
	clock_init();
	GPIO_init();
	NVIC_init();
	EXTI0_setCallBackFun(EXTI_Task);
	EXTI_init(&EXTI0_Config);
	EXTI_enable(EXTI0);
	/* Loop forever */
	for(;;){
	}
}
