/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/
#include "lcd.h"
#include "keypad.h"
#include "stm32f103x6.h"
#include "delay.h"
#include "gpio.h"

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void clock_init(){
	//Enable GPIOA Clock
	RCC_GPIOA_CLK_EN();
	//Enable GPIOB Clock
	RCC_GPIOB_CLK_EN();
	delay_ms(1);
}
void SevenSegment_GPIO_init(){
	uint32 i;
	GPIO_PinConfig_t Pin_Config={GPIO_PIN_9,GPIO_OUTPUT_PP,GPIO_SPEED_2_MHZ};
	//Configure GPIOB Pins[9-15] as output push pull
	for(i=0;i<7;i++){
		MCAL_GPIO_init(GPIO_PORTB, &Pin_Config);
		Pin_Config.Pin_Num++;
	}
}
int main(void)
{
	uint8 key=0;
	uint32 i;
	clock_init();
	LCD_init();
	SevenSegment_GPIO_init();
	unsigned char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	unsigned char DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	//Display Numbers from 0 to 9 on 7-Segment and LCD
	for(i=0;i<11;i++){
		MCAL_GPIO_writeGroub(GPIO_PORTB, 0x7F,GPIO_PIN_9,DISPLAY[i]);
		LCD_displayCharacter(LCD_DISPLAY[i]);
		delay_ms(2000);
	}
	LCD_cleanScreen();
	Keypad_init();
	LCD_displayString("Keypad is Ready");
	delay_ms(2000);
	LCD_cleanScreen();
    /* Loop forever */
	while(1){
		key=Keypad_getKey();
		switch(key){
		case ' ':
			LCD_cleanScreen();
			break;
		case KEYPAD_NOT_PRESSED:
			break;
		default:
			LCD_displayCharacter(key);
			if(key >='0' && key <= '9'){
				MCAL_GPIO_writeGroub(GPIO_PORTB, 0x7F,GPIO_PIN_9,DISPLAY[(key-'0')]);
			}
			break;
		}
	}

}
