/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"

#define RCC_BASE      0x040021000
#define PortA_BASE    0x040010800

#define RCC_APB2ENR   *(volatile uint32*) (RCC_BASE+0x18)
#define GPIOA_CRH     *(volatile uint32*) (PortA_BASE+0x04)
#define GPIOA_ODR     *(volatile uint32*) (PortA_BASE+0x0C)

int main(void)
{
	uint32 i;
	RCC_APB2ENR|=(1<<2);
	GPIOA_CRH=(GPIOA_CRH&(0xff0fffff))|(0x00200000);
	/* Loop forever */
	for(;;){
		GPIOA_ODR|=(1<<13);
		for(i=0;i<5000;i++);
		GPIOA_ODR&=~(1<<13);
		for(i=0;i<5000;i++);
	}
	return 0;
}
